name=Adafruit TMAG5273
version=1.0.0
author=Adafruit
maintainer=Adafruit <info@adafruit.com>
sentence=Arduino library for the TI TMAG5273 3-axis Hall-effect sensor
paragraph=Arduino library for the TI TMAG5273 low-power linear 3D Hall-effect magnetic sensor with I2C interface. Supports all TMAG5273 variants (A1/A2/B1/B2/C1/C2/D1/D2).
category=Sensors
url=https://github.com/adafruit/Adafruit_TMAG5273
architectures=*
depends=Adafruit BusIO, Adafruit Unified Sensor
